version: '3.8'
services:
  nginx:
    build:
      context: .
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html:ro
      - ./cgi:/usr/share/nginx/cgi
